name: Continuos Delivery

#El proceso se inicia en cada push (de cualquier branch)
#on: [push]

#Solo en push a master
on:
  push:
    branches:
      - master

jobs:
  continuos-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar la última versión del código
        uses: actions/checkout@v4

      - name: Configurar node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm install
  continuos-deployment:
  runs-on: ubuntu-latest
  steps:
    - name: Deploy on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          cd ProyectoBeduModuloNodeEquipo1 
          git pull origin master
          npm install --production
          pm2 restart index.js
